apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: 982005835062.dkr.ecr.ap-south-1.amazonaws.com/api-gateway:v1
        ports:
        - containerPort: 3000
        env:
        - name: PRODUCTS_SERVICE_URL
          value: "http://products-service:3001"
        - name: ORDERS_SERVICE_URL
          value: "http://orders-service:3002"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
